exports.Buildings = [
    { label: 'Academic Surge', value: 'ACAD', className: 'buildingName' },
    { label: 'Aggie Stadium', value: 'aggiestadium', className: 'buildingName' },
    { label: 'amrl', value: 'AMRL', className: 'buildingName' },
    { label: 'Activities and Recreation Center', value: 'ARC', className: 'buildingName' },
    { label: 'arcpavilion', value: 'arcpavilion', className: 'buildingName' },
    { label: 'Art Building', value: 'ART', className: 'buildingName' },
    { label: 'Art Building Annex', value: 'ARTX', className: 'buildingName' },
    { label: 'Advanced Transportation Infrastructure Research Center', value: 'atirc', className: 'buildingName' },
    { label: 'Bainer Hall', value: 'Bainer', className: 'buildingName' },
    { label: 'Briggs Hall', value: 'BRIG', className: 'buildingName' },
    { label: 'CAAN 4684', value: 'caan_4684', className: 'buildingName' },
    { label: 'CAAN 4874', value: 'caan_4874', className: 'buildingName' },
    { label: 'CAAN 4880', value: 'caan_4880', className: 'buildingName' },
    { label: 'CAAN 4888', value: 'caan_4888', className: 'buildingName' },
    { label: 'CAAN 4923', value: 'caan_4923', className: 'buildingName' },
    { label: 'Campus Data Center', value: 'campusdatacenter', className: 'buildingName' },
    { label: 'Center for Companion Animal Health (CCAH)', value: 'ccah', className: 'buildingName' },
    { label: 'Chemistry', value: 'CHEM', className: 'buildingName' },
    { label: 'Chemistry Annex', value: 'CHEMX', className: 'buildingName' },
    { label: 'University Conference Center', value: 'conferencecenter', className: 'buildingName' },
    { label: 'IET Communications Resources Complex', value: 'criet', className: 'buildingName' },
    { label: 'Cruess Hall', value: 'CRUS', className: 'buildingName' },
    { label: 'Dutton Hall', value: 'dutton', className: 'buildingName' },
    { label: 'Earth and Physical Sciences Building', value: 'EPS', className: 'buildingName' },
    { label: 'Maddy Lab (Equine Analytical Lab)', value: 'eqacl', className: 'buildingName' },
    { label: 'FPS Trinchero Family Estates Building', value: 'FPS', className: 'buildingName' },
    { label: 'Freeborn Hall', value: 'freeborn', className: 'buildingName' },
    { label: 'Genome & Biomedical Sciences', value: 'GBSF', className: 'buildingName' },
    { label: 'Ghausi Hall', value: 'GHA', className: 'buildingName' },
    { label: 'Giedt Hall', value: 'GIEDT', className: 'buildingName' },
    { label: 'Gallagher Hall', value: 'GSM', className: 'buildingName' },
    { label: 'Haring Hall', value: 'haring', className: 'buildingName' },
    { label: 'Hart Hall', value: 'HART', className: 'buildingName' },
    { label: 'Student Health & Wellness Center', value: 'healthwellness', className: 'buildingName' },
    { label: 'Heitman Staff Learning Center', value: 'heitmanslc', className: 'buildingName' },
    { label: 'Hoagland Hall', value: 'hoagland', className: 'buildingName' },
    { label: 'Housing Administration', value: 'housingadmin', className: 'buildingName' },
    { label: 'Hopkins Services Complex', value: 'hsup', className: 'buildingName' },
    { label: 'Hunt Hall', value: 'hunt', className: 'buildingName' },
    { label: 'Hutchison Hall', value: 'HUTCH', className: 'buildingName' },
    { label: 'Hutchison Child Development Center', value: 'hutchison.cdc', className: 'buildingName' },
    { label: 'International Center', value: 'international_center', className: 'buildingName' },
    { label: 'Jungerman Hall', value: 'JUNGER', className: 'buildingName' },
    { label: 'Kemper Hall', value: 'kemper', className: 'buildingName' },
    { label: 'Kerr Hall', value: 'KERR', className: 'buildingName' },
    { label: 'King Hall', value: 'KING', className: 'buildingName' },
    { label: 'Life Sciences', value: 'LSA', className: 'buildingName' },
    { label: 'Mathematical Sciences Building', value: 'MATH', className: 'buildingName' },
    { label: 'Medical Sciences 1D', value: 'medsci1d', className: 'buildingName' },
    { label: 'Meyer Hall', value: 'MEYR', className: 'buildingName' },
    { label: 'Mrak Hall', value: 'MRAK', className: 'buildingName' },
    { label: 'Memorial Union', value: 'MU', className: 'buildingName' },
    { label: 'Music Building', value: 'MUSIC', className: 'buildingName' },
    { label: 'Olson Hall', value: 'OLS', className: 'buildingName' },
    { label: 'Parsons Seed Certification Center', value: 'parsons', className: 'buildingName' },
    { label: 'Pavilion Parking Structure', value: 'pavilionparking', className: 'buildingName' },
    { label: 'Plant & Environmental Sciences', value: 'PES_ICS', className: 'buildingName' },
    { label: 'Physics Building', value: 'physics', className: 'buildingName' },
    { label: 'Roessler Hall', value: 'physics.roessler', className: 'buildingName' },
    { label: 'Ann E. Pitzer Center', value: 'pitzer_center', className: 'buildingName' },
    { label: 'Physical Sciences & Engineering Library', value: 'pselibrary', className: 'buildingName' },
    { label: 'Quad Parking Structure', value: 'quadparking', className: 'buildingName' },
    { label: 'Rifle Range', value: 'riflerange', className: 'buildingName' },
    { label: 'Robert Mondavi Institute', value: 'rmi', className: 'buildingName' },
    { label: 'RMI Brewery, Winery, and Food Pilot Facility', value: 'rmi.bwfp', className: 'buildingName' },
    { label: 'Robbins Hall', value: 'ROBN', className: 'buildingName' },
    { label: 'Student Community Center', value: 'SCC', className: 'buildingName' },
    { label: 'Schaal Aquatic Center', value: 'schaal', className: 'buildingName' },
    { label: 'Sciences Lab Building and Lecture Hall', value: 'scilab', className: 'buildingName' },
    { label: 'Segundo High Rises', value: 'segundo.highrises', className: 'buildingName' },
    { label: 'Segundo North', value: 'segundo.north', className: 'buildingName' },
    { label: 'Segundo Regan', value: 'segundo.regan', className: 'buildingName' },
    { label: 'Segundo Dining Commons', value: 'SEGU', className: 'buildingName' },
    { label: 'Segundo Services Center', value: 'segundoservices', className: 'buildingName' },
    { label: 'Shields Library', value: 'SHIELDS', className: 'buildingName' },
    { label: 'Manetti Shrem Museum of Art', value: 'shrem_museum', className: 'buildingName' },
    { label: 'Social Sciences & Humanities', value: 'SOCS', className: 'buildingName' },
    { label: 'Sproul Hall', value: 'sproul', className: 'buildingName' },
    { label: 'Storer Hall', value: 'STOR', className: 'buildingName' },
    { label: 'Transportation and Parking Services', value: 'taps', className: 'buildingName' },
    { label: 'Tercero 1', value: 'TER1', className: 'buildingName' },
    { label: 'Tercero 2', value: 'TER2', className: 'buildingName' },
    { label: 'Tercero 3', value: 'tercero3', className: 'buildingName' },
    { label: 'Tercero Dining Commons & Services Center', value: 'TERC', className: 'buildingName' },
    { label: 'Tupper Hall', value: 'TUPP', className: 'buildingName' },
    { label: 'University Services', value: 'university_services', className: 'buildingName' },
    { label: 'Hoffman Equine Athletic Performance Laboratory', value: 'vm.eapl', className: 'buildingName' },
    { label: 'Veterinary Medicine 2', value: 'VM2', className: 'buildingName' },
    { label: 'Veterinary Medicine 3A', value: 'VM3A', className: 'buildingName' },
    { label: 'Veterinary Medicine 3B', value: 'VM3B', className: 'buildingName' },
    { label: 'Valley Hall', value: 'VMIF', className: 'buildingName' },
    { label: 'Veterinary Medical Teaching Hospital', value: 'VMTH', className: 'buildingName' },
    { label: 'VMTH Surgical', value: 'vmthsurgical', className: 'buildingName' },
    { label: 'VMTH Ward', value: 'vmthward', className: 'buildingName' },
    { label: 'Voorhies Hall', value: 'voorhies', className: 'buildingName' },
    { label: 'Watershed Science Facility', value: 'WSRC', className: 'buildingName' },
    { label: 'Wellman Hall', value: 'WELL', className: 'buildingName' },
    { label: 'Western Human Nutrition Research Center', value: 'whnrc', className: 'buildingName' },
    { label: 'Wickson Hall', value: 'WICK', className: 'buildingName' },
    { label: 'Wright Hall', value: 'wright', className: 'buildingName' },
    { label: 'Young Hall', value: 'YOUNG', className: 'buildingName' },

];
